#!/bin/bash
ak="$1"
rp="$2"
hash="$(python3 $(pwd)/osu.py $rp -n)"
sr="$(python3 $(pwd)/sr.py $ak $hash)"
user="$(python3 $(pwd)/osu.py $rp -b)"
map="$(python3 $(pwd)/map.py $ak $hash)"
mods="$(python3 $(pwd)/osu.py $rp -k)"
acc="$(python3 $(pwd)/osu.py $rp -m)"
echo "$sr⭐ $user | $map $acc"
